language: node_js
node_js: node
before_script:
- npm install -g gitbook-cli
script: 
- gitbook install
- gitbook build
- cp icons/* _book/gitbook/images
deploy:
  local_dir: _book
  provider: pages
  skip_cleanup: true
  name: Travis Build Bot
  fqdn:
  keep_history: true
  on:
    branch: master
  target_branch: gh-pages
  # committer_from_gh: true
  # allow_empty_commit: true
  github_token:
    secure: IlW4/OKOtzB3pXWmCj8286X05hT3Qmlt4gb8yFo59BsS6cj2s5z4fHdpaxiGmsu1dtfhQnnphb0xdHXvvkDahs5FNkICwmFJezFjiP21Cbadf0LPvhyADQHTVw5SlP9ofI0l+t6+y/vHPpsrF0tEXMutcSeRfbphWcLAkZDEkfu6X8PE5yNfUJxhfF/ULEWiXcJFv69Oac4U5mGOZDgHAZGNRiVN6NPajknA/dYCubsBfAIi6hAuX7HKaILbacNkz3XHUaKqgwh8MPdRITzuaiPeU7w5T0RKHHZ5wgkbe5cvoEDSrnsuBCeJaCUjaBJZZYMG25yCV/AxZcDMlz9YE4HUXNWp1vgjZKd6KE+lk9xA11MGqu7Mt23+0jkhkYgqNCWX/9tN5v/DXQ3D2zkmniwzb6iWk2Ui2CtDKIYZdUQupq0hqSvuwWWw4yXjAZau4EF8zG65lroVTpPfQZwxkiooHh8XnCJGxwu9H99iU8EPjxeG2l72jceqQtbkFaotEbdmdTENC5IE4slW+5j4oSWCoGwtmOu4aW+3Ofsxw1t/ryftDIe6kxO1QTIQ4DFw9oE0peEPTrP5mD6I7RsihyBL69/co6VE1ciUCaukrCfGpnrPJOGB88xFUg2kUF4AFLmnlu6jOAtMjGGcux4t+Tje8GpSYqgv8bTc/2WA8Uo=
